version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: auth-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  auth-service:
    build: .
    container_name: auth-service
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    ports:
      - '5000:5000'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mongo-data:
